---
name: IO-Handle-Moose
version: 0.0101
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: Moose reimplementation of IO::Handle with improvements
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Base: 0.12
  Exception::System: 0.07
  File::Stat::Moose: 0
  MooseX::GlobRef::Object: 0.02
  perl: 5.006
build_requires:
  Test::Unit::Lite: 0.09
provides:
  IO::Handle::Moose:
    file: lib/IO/Handle/Moose.pm
    version: 0.0101
  IO::Handle::Moose::Syscall:
    file: lib/IO/Handle/Moose.pm
  IO::Handle::Moose::Tie:
    file: lib/IO/Handle/Moose.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
